package com.sovren.models.api.bimetricscoring;

import com.sovren.models.job.ParsedJob;

/**
* A Sovren.Models.Job.ParsedJob and id pair for a bimetric score request
*/
public class ParsedJobWithId implements IParsedDocWithId  {
    
    /** The id of the document (used in the response body)*/
    public String Id;

    /** A job generated by the Sovren parser*/
    public ParsedJob JobData;

    @Override
    public String getDocId() {
        return Id;
    }
}
