package com.sovren.models.api.bimetricscoring;

import com.sovren.models.resume.ParsedResume;

/**
* A Sovren.Models.Resume.ParsedResume and id pair for a bimetric score request
*/
public class ParsedResumeWithId implements IParsedDocWithId {
    
    /** The id of the document (used in the response body)*/
    public String Id;
    
    /** A resume generated by the Sovren parser*/
    public ParsedResume ResumeData;

    @Override
    public String getDocId() {
        return Id;
    }
}
