package com.sovren.models.api.matching;

import com.sovren.models.api.matching.request.MatchRequest;
import com.sovren.models.resume.ParsedResume;

/**
* Request body for a Match request
*/
public class MatchResumeRequest extends MatchRequest {
    
    /** The resume to match. This should be generated by parsing a resume with the Sovren Resume Parser.*/
    public ParsedResume ResumeData;
}
