package com.sovren.models.api.matching;

import com.sovren.models.api.matching.request.MatchRequest;
import com.sovren.models.job.ParsedJob;

/**
* Request body for a Match request
*/
public class MatchJobRequest extends MatchRequest {
    
    /** The job to match. This should be generated by parsing a job with the Sovren Job Parser.*/
    public ParsedJob JobData;
}
