// Copyright © 2020 Sovren Group, Inc. All rights reserved.
// This file is provided for use by, or on behalf of, Sovren licensees
// within the terms of their license of Sovren products or Sovren customers
// within the Terms of Service pertaining to the Sovren SaaS products.

package com.sovren.models.api.bimetricscoring;

import com.sovren.models.resume.ParsedResume;

/**
* A Sovren.Models.Resume.ParsedResume and id pair for a bimetric score request
*/
public class ParsedResumeWithId implements IParsedDocWithId {
    
    /** The id of the document (used in the response body)*/
    public String Id;
    
    /** A resume generated by the Sovren parser*/
    public ParsedResume ResumeData;

    @Override
    public String getDocId() {
        return Id;
    }
}
