# This workflow will generate javadocs, build, and test a package using Maven

name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B compile --file pom.xml
      
  unit-tests:
    runs-on: ubuntu-latest
    # only run this if we have already generated javadocs in last commit
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create credentials file
      run: 'echo "$CREDENTIALS_FILE" > ./src/test/resources/credentials.json'
      shell: bash
      env:
        CREDENTIALS_FILE: ${{secrets.TEST_CREDENTIALS}}
    - name: Test with Maven
      run: mvn test --fail-at-end --file pom.xml
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
